version: '3'
services:
  cassandra:
    image: cassandra:3.11
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  producer:
    depends_on:
      - kafka
    build:
      context: .
      dockerfile: producer.dockerfile
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_TOPIC: mytopic
      DEVICES_AMOUNT: 10
      DEVICES_TIMEOUT: 1000
  consumer:
    restart: on-failure
    depends_on:
      - kafka
      - cassandra
    build:
      context: .
      dockerfile: consumer.dockerfile
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_TOPIC: mytopic
      CASSANDRA_SERVERS: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: relay
  api:
    restart: on-failure
    depends_on:
      - cassandra
      - consumer
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - 8080:8080
    environment:
      CASSANDRA_SERVERS: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: relay
